<a href="https://colab.research.google.com/github/muskan-cloud/Learning-NLP/blob/main/NER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
from IPython.display import HTML

In [67]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [68]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [69]:
doc  = nlp("Tesla Inc acquired Twitter Inc for $45 billion.")

for ent in doc.ents:
  print(ent.text , " | " ,ent.label_ , " | ", spacy.explain(ent.label_) )

Tesla Inc  |  ORG  |  Companies, agencies, institutions, etc.
Twitter Inc  |  ORG  |  Companies, agencies, institutions, etc.
$45 billion  |  MONEY  |  Monetary values, including unit

In [70]:
from spacy import displacy
# Assuming 'html_content' is the HTML output generated by displacy.render
html_content = displacy.render(doc,style="ent")

# Display the HTML content directly in a Colab cell
HTML(html_content)

In [71]:
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [72]:
doc = nlp("Michael Bloomberg founded BLOOMBERG L.P in 1982")

for ent in doc.ents:
  print(ent.text , " | ", ent.label_ , " | ", spacy.explain(ent.label_))

Michael Bloomberg  |  PERSON  |  People, including fictional
BLOOMBERG L.P  |  ORG  |  Companies, agencies, institutions, etc.
1982  |  DATE  |  Absolute or relative dates or periods

In [73]:
html_content = displacy.render(doc, style = "ent")
HTML(html_content)

***when company is not recognized we manually set them.***

In [81]:
doc = nlp("Tesla Inc acquired twitter for $45 billion.")

In [82]:
type(doc[2:5])

spacy.tokens.span.Span

In [83]:
from spacy.tokens import Span

In [84]:
s1 = Span(doc,0,1,label = "ORG")
s2 = Span(doc,3,4,label = "ORG")

doc.set_ents([s1,s2],default = "unmodified")

In [85]:
for ent in doc.ents:
  print(ent.text, " | ",ent.label_)

Tesla Inc  |  ORG
twitter  |  ORG
$45 billion  |  MONEY